=begin
#Waitlisted API

#Waitlisted API

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for Waitlisted::ReservationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ReservationApi' do
  before do
    # run before each test
    @instance = Waitlisted::ReservationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReservationApi' do
    it 'should create an instact of ReservationApi' do
      expect(@instance).to be_instance_of(Waitlisted::ReservationApi)
    end
  end

  # unit tests for create_reservation
  # 
  # Creates a new reservation.
  # @param body Reservation Data
  # @param [Hash] opts the optional parameters
  # @return [ReservationsResponse]
  describe 'create_reservation test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_reservation
  # 
  # Delete a reservation.
  # @param body Reservation Data
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_reservation test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_reservation
  # 
  # Get a reservation.
  # @param email Email address
  # @param [Hash] opts the optional parameters
  # @return [ReservationsResponse]
  describe 'get_reservation test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
