=begin
#Waitlisted API

#Waitlisted API

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for Waitlisted::SiteApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SiteApi' do
  before do
    # run before each test
    @instance = Waitlisted::SiteApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SiteApi' do
    it 'should create an instact of SiteApi' do
      expect(@instance).to be_instance_of(Waitlisted::SiteApi)
    end
  end

  # unit tests for get_site
  # 
  # Get site settings and reservation count.
  # @param [Hash] opts the optional parameters
  # @return [SiteResponse]
  describe 'get_site test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
