=begin
#Waitlisted API

#Waitlisted API

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'date'

module Waitlisted

  class SiteResponse
    attr_accessor :id

    attr_accessor :brand_color

    attr_accessor :button_text_color

    attr_accessor :custom_styles

    attr_accessor :ask_name

    attr_accessor :signup_title

    attr_accessor :signup_copy

    attr_accessor :position_title

    attr_accessor :social_copy

    attr_accessor :social_message

    attr_accessor :domain

    attr_accessor :share_social_copy

    attr_accessor :referral_copy

    attr_accessor :check_position_copy

    attr_accessor :join_button_copy

    attr_accessor :check_reservation_copy

    attr_accessor :email_field_label

    attr_accessor :name_field_label

    attr_accessor :thank_you_share_template

    attr_accessor :waitlist_threshold

    attr_accessor :use_custom_thank_you

    attr_accessor :hide_waitlist

    attr_accessor :unmet_shared_template

    attr_accessor :threshold_met

    attr_accessor :website_url

    attr_accessor :tracking_code

    attr_accessor :custom_css

    attr_accessor :hide_branding

    attr_accessor :total_count


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'brand_color' => :'brand_color',
        :'button_text_color' => :'button_text_color',
        :'custom_styles' => :'custom_styles',
        :'ask_name' => :'ask_name',
        :'signup_title' => :'signup_title',
        :'signup_copy' => :'signup_copy',
        :'position_title' => :'position_title',
        :'social_copy' => :'social_copy',
        :'social_message' => :'social_message',
        :'domain' => :'domain',
        :'share_social_copy' => :'share_social_copy',
        :'referral_copy' => :'referral_copy',
        :'check_position_copy' => :'check_position_copy',
        :'join_button_copy' => :'join_button_copy',
        :'check_reservation_copy' => :'check_reservation_copy',
        :'email_field_label' => :'email_field_label',
        :'name_field_label' => :'name_field_label',
        :'thank_you_share_template' => :'thank_you_share_template',
        :'waitlist_threshold' => :'waitlist_threshold',
        :'use_custom_thank_you' => :'use_custom_thank_you',
        :'hide_waitlist' => :'hide_waitlist',
        :'unmet_shared_template' => :'unmet_shared_template',
        :'threshold_met' => :'threshold_met',
        :'website_url' => :'website_url',
        :'tracking_code' => :'tracking_code',
        :'custom_css' => :'custom_css',
        :'hide_branding' => :'hide_branding',
        :'total_count' => :'total_count'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'id' => :'String',
        :'brand_color' => :'String',
        :'button_text_color' => :'String',
        :'custom_styles' => :'String',
        :'ask_name' => :'BOOLEAN',
        :'signup_title' => :'String',
        :'signup_copy' => :'String',
        :'position_title' => :'String',
        :'social_copy' => :'String',
        :'social_message' => :'String',
        :'domain' => :'String',
        :'share_social_copy' => :'String',
        :'referral_copy' => :'String',
        :'check_position_copy' => :'String',
        :'join_button_copy' => :'String',
        :'check_reservation_copy' => :'String',
        :'email_field_label' => :'String',
        :'name_field_label' => :'String',
        :'thank_you_share_template' => :'String',
        :'waitlist_threshold' => :'Integer',
        :'use_custom_thank_you' => :'BOOLEAN',
        :'hide_waitlist' => :'BOOLEAN',
        :'unmet_shared_template' => :'String',
        :'threshold_met' => :'BOOLEAN',
        :'website_url' => :'String',
        :'tracking_code' => :'String',
        :'custom_css' => :'String',
        :'hide_branding' => :'BOOLEAN',
        :'total_count' => :'Integer'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.has_key?(:'brand_color')
        self.brand_color = attributes[:'brand_color']
      end

      if attributes.has_key?(:'button_text_color')
        self.button_text_color = attributes[:'button_text_color']
      end

      if attributes.has_key?(:'custom_styles')
        self.custom_styles = attributes[:'custom_styles']
      end

      if attributes.has_key?(:'ask_name')
        self.ask_name = attributes[:'ask_name']
      end

      if attributes.has_key?(:'signup_title')
        self.signup_title = attributes[:'signup_title']
      end

      if attributes.has_key?(:'signup_copy')
        self.signup_copy = attributes[:'signup_copy']
      end

      if attributes.has_key?(:'position_title')
        self.position_title = attributes[:'position_title']
      end

      if attributes.has_key?(:'social_copy')
        self.social_copy = attributes[:'social_copy']
      end

      if attributes.has_key?(:'social_message')
        self.social_message = attributes[:'social_message']
      end

      if attributes.has_key?(:'domain')
        self.domain = attributes[:'domain']
      end

      if attributes.has_key?(:'share_social_copy')
        self.share_social_copy = attributes[:'share_social_copy']
      end

      if attributes.has_key?(:'referral_copy')
        self.referral_copy = attributes[:'referral_copy']
      end

      if attributes.has_key?(:'check_position_copy')
        self.check_position_copy = attributes[:'check_position_copy']
      end

      if attributes.has_key?(:'join_button_copy')
        self.join_button_copy = attributes[:'join_button_copy']
      end

      if attributes.has_key?(:'check_reservation_copy')
        self.check_reservation_copy = attributes[:'check_reservation_copy']
      end

      if attributes.has_key?(:'email_field_label')
        self.email_field_label = attributes[:'email_field_label']
      end

      if attributes.has_key?(:'name_field_label')
        self.name_field_label = attributes[:'name_field_label']
      end

      if attributes.has_key?(:'thank_you_share_template')
        self.thank_you_share_template = attributes[:'thank_you_share_template']
      end

      if attributes.has_key?(:'waitlist_threshold')
        self.waitlist_threshold = attributes[:'waitlist_threshold']
      end

      if attributes.has_key?(:'use_custom_thank_you')
        self.use_custom_thank_you = attributes[:'use_custom_thank_you']
      end

      if attributes.has_key?(:'hide_waitlist')
        self.hide_waitlist = attributes[:'hide_waitlist']
      end

      if attributes.has_key?(:'unmet_shared_template')
        self.unmet_shared_template = attributes[:'unmet_shared_template']
      end

      if attributes.has_key?(:'threshold_met')
        self.threshold_met = attributes[:'threshold_met']
      end

      if attributes.has_key?(:'website_url')
        self.website_url = attributes[:'website_url']
      end

      if attributes.has_key?(:'tracking_code')
        self.tracking_code = attributes[:'tracking_code']
      end

      if attributes.has_key?(:'custom_css')
        self.custom_css = attributes[:'custom_css']
      end

      if attributes.has_key?(:'hide_branding')
        self.hide_branding = attributes[:'hide_branding']
      end

      if attributes.has_key?(:'total_count')
        self.total_count = attributes[:'total_count']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          brand_color == o.brand_color &&
          button_text_color == o.button_text_color &&
          custom_styles == o.custom_styles &&
          ask_name == o.ask_name &&
          signup_title == o.signup_title &&
          signup_copy == o.signup_copy &&
          position_title == o.position_title &&
          social_copy == o.social_copy &&
          social_message == o.social_message &&
          domain == o.domain &&
          share_social_copy == o.share_social_copy &&
          referral_copy == o.referral_copy &&
          check_position_copy == o.check_position_copy &&
          join_button_copy == o.join_button_copy &&
          check_reservation_copy == o.check_reservation_copy &&
          email_field_label == o.email_field_label &&
          name_field_label == o.name_field_label &&
          thank_you_share_template == o.thank_you_share_template &&
          waitlist_threshold == o.waitlist_threshold &&
          use_custom_thank_you == o.use_custom_thank_you &&
          hide_waitlist == o.hide_waitlist &&
          unmet_shared_template == o.unmet_shared_template &&
          threshold_met == o.threshold_met &&
          website_url == o.website_url &&
          tracking_code == o.tracking_code &&
          custom_css == o.custom_css &&
          hide_branding == o.hide_branding &&
          total_count == o.total_count
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [id, brand_color, button_text_color, custom_styles, ask_name, signup_title, signup_copy, position_title, social_copy, social_message, domain, share_social_copy, referral_copy, check_position_copy, join_button_copy, check_reservation_copy, email_field_label, name_field_label, thank_you_share_template, waitlist_threshold, use_custom_thank_you, hide_waitlist, unmet_shared_template, threshold_met, website_url, tracking_code, custom_css, hide_branding, total_count].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = Waitlisted.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
